#ifndef _CONFIGDEFS_
#define _CONFIGDEFS_ 1

#define DYNAMORIO_DEFINES "-DINTERNAL -DDEBUG -DDRSTATS_DEMO -DX86 -DWINDOWS -DCLIENT_INTERFACE -DAPP_EXPORTS -DKSTATS -DBUILD_TESTS -DANNOTATIONS -DNOLIBC -DASSEMBLE_WITH_MASM -DHAVE_MEMINFO -DHAVE_MEMINFO_QUERY -DWINDOWS_PC_SAMPLE -DDYNAMORIO_IR_EXPORTS -DCUSTOM_TRACES -DCLIENT_SIDELINE -DDR_APP_EXPORTS -DDEBUG_MEMORY -DHEAP_ACCOUNTING -DDEADLOCK_AVOIDANCE -DSHARING_STUDY -DHASHTABLE_STATISTICS"

#endif /* _CONFIGDEFS_ */
